app/users/models/followers.py
"""
    app.users.models.followers
    ~~~~~~~~~~~~~~~~~~~~~~~~~~

    Followers model.
"""
from datetime import datetime
from app.extensions import db


followers = db.Table(
    'followers',
    db.Column('follower_id', db.Integer, db.ForeignKey('user.id')),
    db.Column('followed_id', db.Integer, db.ForeignKey('user.id')),
    db.Column('created', db.DateTime, default=datetime.utcnow)
)

app/users/forms.py
import re
from flask_login import current_user
from flask_wtf import FlaskForm
from flask_wtf.file import FileRequired, FileField, FileAllowed
from wtforms import (
    StringField, SubmitField, TextAreaField, PasswordField, SelectField
)
from wtforms.validators import (
    ValidationError, DataRequired, Email, Length, EqualTo
)
from app.users.models.user import User


class PostForm(FlaskForm):
    body = TextAreaField('Say something', validators=[DataRequired()])
    submit = SubmitField('Post')


class SearchForm(FlaskForm):
    search = StringField('Search', validators=[DataRequired(), Length(min=3)])
    submit = SubmitField('Search')


class SettingsAccountForm(FlaskForm):
    username = StringField('Username',
                           validators=[DataRequired(), Length(max=35)])
    email = StringField('Email',
                        validators=[DataRequired(), Email(), Length(max=255)])
    submit = SubmitField('Update Account')

    def __init__(self, original_username, original_email, *args, **kwargs):
        super(SettingsAccountForm, self).__init__(*args, **kwargs)
        self.original_username = original_username
        self.original_email = original_email

    def validate_username(self, username):
        # Make sure ``username``:
        # - Has alphanumeric / underscore
        # - Starts with alpha
        # - Doesn't start or end with an underscore
        regex = '^[a-zA-Z][a-zA-Z1-9_]*[a-zA-Z0-9]+$'
        if not re.match(regex, username.data):
            raise ValidationError('Invalid username. Example: john_doe13')

        if username.data != self.original_username:
            user = User.query.filter_by(username=self.username.data).first()
            if user is not None:
                raise ValidationError('Please use a different username.')

    def validate_email(self, email):
        if email.data != self.original_email:
            user = User.query.filter_by(email=self.email.data).first()
            if user is not None:
                raise ValidationError('Please use a different email.')


class SettingsProfileForm(FlaskForm):
    first_name = StringField('First name',
                             validators=[DataRequired(), Length(max=35)])
    last_name = StringField('Last name',
                            validators=[DataRequired(), Length(max=35)])
    profile_picture = FileField(
        'Profile picture',
        validators=[
            FileAllowed(
                ['jpg', 'png', 'jpeg'],
                '.jpg, .jpeg, and .png file extensions only.'
            )
        ])
    bio = TextAreaField('Bio', validators=[Length(max=500)])
    location = StringField('Location', validators=[Length(max=255)])
    website_url = StringField('Website', validators=[Length(max=500)])
    submit = SubmitField('Update Profile')


class SettingsPasswordForm(FlaskForm):
    current_password = PasswordField(
        'Old password', validators=[DataRequired()])
    password = PasswordField(
        'New password',
        validators=[DataRequired(), Length(min=8, max=32)])
    password2 = PasswordField(
        'Confirm new password',
        validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Update Password')

    def validate_current_password(self, current_password):
        if not current_user.check_password(current_password.data):
            raise ValidationError('Incorrect password.')


class SettingsMiscellaneousForm(FlaskForm):
    posts_per_page = SelectField(
        'Items per page to display',
        choices=[
            ('5', '5'),
            ('10', '10'), 
            ('20', '20'), 
            ('50', '50'), 
            ('75', '75'), 
            ('100', '100')
        ])
    submit = SubmitField('Update')


class SettingsDeleteAccountForm(FlaskForm):
    username = StringField(
        'Enter your username', validators=[DataRequired()])
    password = PasswordField(
        'Confirm your password', validators=[DataRequired()])
    submit = SubmitField('Delete Account')

    def validate_username(self, username):
        if current_user.username != username.data:
            raise ValidationError(
                'Incorrect username. Make sure you type your username '
                'exactly as it is.')

    def validate_password(self, password):
        if not current_user.check_password(password.data):
            raise ValidationError('Incorrect password.')

app/users/views.py
"""
    app.users.views
    ~~~~~~~~~~~~~~~

    Views for users.
"""
import os
from datetime import datetime
from sqlalchemy import or_
from flask import Blueprint, render_template, redirect, request, url_for, flash
from flask_login import login_required, current_user
from app.extensions import db
from app.helpers import ProfilePhoto
from app.users.models.user import User
from app.users.models.posts import (
    Post, PostLike, PostComment, PostCommentLike, PostEdit, PostCommentEdit
)
from app.users.models.notification import NotificationHelper
from app.users.forms import (
    PostForm, SettingsAccountForm, SettingsProfileForm, SettingsPasswordForm,
    SearchForm, SettingsMiscellaneousForm, SettingsDeleteAccountForm
)


users = Blueprint('users', __name__)


@users.before_request
def before_request():
    if current_user.is_authenticated:
        if not current_user.active:
            return redirect(url_for('static_views.logout'))
        current_user.last_seen = datetime.utcnow()
        current_user.commit()


@users.route('/home', methods=['GET', 'POST'])
@login_required
def home():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(body=form.body.data, author=current_user,
                    recipient=current_user)
        post.commit()
        flash('Your post is now live!')
        return redirect(url_for('users.home'))
    page = request.args.get('page', 1, type=int)
    posts = current_user.home_posts.\
        paginate(page, current_user.posts_per_page, False)
    unfollowed_posts = current_user.unfollowed_posts.limit(4).all()
    return render_template('users/home.html', form=form, posts=posts,
                           unfollowed_posts=unfollowed_posts,
                           user=current_user)


@users.route('/<username>/posts')
@login_required
def my_posts(username):
    user = User.query.filter_by(username=username, active=True).first_or_404()
    page = request.args.get('page', 1, type=int)
    posts = user.my_posts.\
        order_by(Post.created.desc()).\
        paginate(page, current_user.posts_per_page, False)
    unfollowed_posts = current_user.unfollowed_posts.limit(8).all()
    return render_template('users/my-posts.html', posts=posts, user=user,
                           unfollowed_posts=unfollowed_posts)


@users.route('/<username>', methods=['GET', 'POST'])
@login_required
def profile(username):
    """ User's profile.

    :param username: username to show profile
    """
    user = User.query.filter_by(username=username, active=True).first_or_404()
    form = PostForm()
    if form.validate_on_submit():
        post = Post(body=form.body.data, author=current_user,
                    recipient=user)
        post = post.commit()
        NotificationHelper(notified=user, notifier=current_user,
                           post=post).post()
        post.commit()
        flash('Your post is now live!')
        return redirect(url_for('users.profile', username=username))
    page = request.args.get('page', 1, type=int)
    posts = user.profile_posts.\
        order_by(Post.created.desc()).\
        paginate(page, current_user.posts_per_page, False)
    return render_template('users/profile.html', user=user, posts=posts,
                           form=form)


@users.route('/<username>/followers', methods=['GET', 'POST'])
@login_required
def followers(username):
    """ Show who is following `username`.

    :param username: username of user to show followers
    """
    user = User.query.filter_by(username=username, active=True).first_or_404()
    page = request.args.get('page', 1, type=int)
    followers = user.get_followers.paginate(
        page, current_user.posts_per_page, False)
    return render_template('users/followers.html', user=user,
                           followers=followers)


@users.route('/<username>/following', methods=['GET', 'POST'])
@login_required
def following(username):
    """ Show who `username` is following.

    :param username: username of user to show following
    """
    user = User.query.filter_by(username=username, active=True).first_or_404()
    page = request.args.get('page', 1, type=int)
    following = user.get_followed.paginate(
        page, current_user.posts_per_page, False)
    return render_template('users/following.html', user=user,
                           following=following)


@users.route('/search', methods=['GET', 'POST'])
@login_required
def search():
    form = SearchForm()
    recent_users = User.query.filter(
        User.active == True, # noqa
        User.id != current_user.id).order_by(
            User.last_seen.desc()).limit(10)
    searchable = '%{}%'.format(request.args.get('search'))
    page = request.args.get('page', 1, type=int)
    search_result = User.query.filter(
        or_(User.first_name.like(searchable),
            User.last_name.like(searchable),
            User.username.like(searchable),
            User.full_name.like(searchable),
            User.email.like(searchable)),
        User.active == True) # noqa
    search_result_count = search_result.count()
    search_result = search_result.paginate(
        page, current_user.posts_per_page, False)
    return render_template(
        'users/search.html', form=form, search_result=search_result,
        recent_users=recent_users, search_result_count=search_result_count)


@users.route('/<username>/<action>')
@login_required
def user_action(username, action):
    """ User actions.

    :param username: Username to take action upon
    :param action: Action to take on `username`
    """
    user = User.query.filter_by(username=username, active=True).first_or_404()
    # Do not allow users to take action on themselves.
    no_self_action = ['follow', 'unfollow']
    if action in no_self_action and user == current_user:
        return redirect(url_for('users.home'))
    # Follow user.
    if action == 'follow':
        current_user.follow(user)
        NotificationHelper(notified=user, notifier=current_user).follow()
        current_user.commit()
        flash('You are now following {}.'.format(user.full_name))
    # Unfollow user.
    if action == 'unfollow':
        current_user.unfollow(user)
        NotificationHelper(notified=user).delete_follow()
        current_user.commit()
        flash('You are no longer following {}.'.format(user.full_name))
    return redirect(request.referrer)


@users.route('/posts/post', methods=['GET', 'POST'])
@login_required
def post():
    post_id = request.args.get('post_id')
    post = Post.post_by_id(post_id).first_or_404()

    comments_page = request.args.get('page', 1, type=int)
    comments = post.active_comments.order_by(
        PostComment.created.asc()).paginate(
            comments_page, current_user.posts_per_page, False)

    likes_page = request.args.get('likes_page', 1, type=int)
    likes = post.active_likes.order_by(
        PostLike.created.desc()).paginate(
            likes_page, current_user.posts_per_page, False)

    form = PostForm()
    if form.validate_on_submit():
        post_comment = PostComment(body=form.body.data, author=current_user,
                                   post_id=post_id)
        comment = post_comment.commit()
        NotificationHelper(notified=comment.post.author,
                           notifier=current_user, comment=comment).comment()
        comment.commit()
        flash('Your post is now live!')
        return redirect(url_for('users.post', post_id=post_id))
    return render_template('users/post.html', post=post, form=form,
                           comments=comments, likes=likes)


@users.route('/posts/post-edit', methods=['GET', 'POST'])
@login_required
def post_edit():
    post_id = request.args.get('post_id')
    post = Post.post_by_id(post_id).first_or_404()
    form = PostForm()
    if form.validate_on_submit():
        # Check to make sure the post was actually edited, and that the
        # user is authorized to make edits on the post.
        if current_user == post.author and not form.body.data == post.body:
            old_post = post.body
            post.body = form.body.data
            post_edit = PostEdit(body=old_post, user_id=current_user.id,
                                 post_id=post.id, created=post.updated)
            db.session.add(post_edit)
            post.commit()
            flash('Your post has been updated.')
            return redirect(url_for('users.post_edit', post_id=post_id))
    elif request.method == 'GET':
        form.body.data = post.body
    return render_template('users/post-edit.html', post=post, form=form)


@users.route('/posts/comment')
@login_required
def comment():
    comment_id = request.args.get('comment_id')
    comment = PostComment.comment_by_id(comment_id).first_or_404()
    page = request.args.get('page', 1, type=int)
    likes = comment.active_likes.order_by(
        PostCommentLike.created.desc()).paginate(
            page, current_user.posts_per_page, False)
    return render_template('users/comment.html', comment=comment,
                           likes=likes)


@users.route('/posts/comment-edit', methods=['GET', 'POST'])
@login_required
def comment_edit():
    comment_id = request.args.get('comment_id')
    comment = PostComment.comment_by_id(comment_id).first_or_404()
    form = PostForm()
    if form.validate_on_submit():
        # Check to make sure the comment was actually edited, and that the
        # user is authorized to make edits on the comment.
        if (current_user == comment.author and
                not form.body.data == comment.body):
            old_comment = comment.body
            comment.body = form.body.data
            comment_edit = PostCommentEdit(
                body=old_comment, user_id=current_user.id,
                comment_id=comment.id, created=comment.updated)
            db.session.add(comment_edit)
            comment.commit()
            flash('Your comment has been updated.')

app/templates/users/_comment.html
<li>
  <div class="post-controls">
    <div class="post-likes">
      {% if current_user.has_liked_comment(comment) %}
      <a href="{{ url_for('users.comment_action', comment_id=comment.id, action='unlike-comment') }}"><i class="fa fa-heart"></i></a>
      {% else %}
      <a href="{{ url_for('users.comment_action', comment_id=comment.id, action='like-comment') }}"><i class="far fa-heart"></i></a>
      {% endif %}
      <a class="post-like-count" href="{{ url_for('users.comment', comment_id=comment.id) }}">
        {{ comment.active_likes.count() }}
      </a>
    </div><!--//END .post-likes-->
    {% if current_user == comment.author %}
    <a href="{{ url_for('users.comment_edit', comment_id=comment.id) }}"><i class="far fa-edit"></i></a>
    {% endif %}
    {% if current_user == comment.author or comment.recipient_id == current_user.id %}
    <a class="delete-post" href="{{ url_for('users.comment_action', comment_id=comment.id, action='delete-comment') }}">
      <i class="fa fa-trash-alt"></i>
    </a>
    {% endif %}
    {% if comment.edits.count() %}
    <a class="comment-edits" href="{{ url_for('users.comment_edit', comment_id=comment.id) }}">
      <span>&mdash;</span>
      edited
    </a>
    {% endif %}
  </div><!--//END .post-controls-->
  <a class="profile-picture" href="{{ url_for('users.profile', username=comment.author.username) }}">
    <img src="{{ url_for('static', filename='img/user/' + comment.author.profile_picture) }}" width="30" height="30">
  </a>
  <p class="comment-body">
    <a href="{{ url_for('users.profile', username=comment.author.username) }}">
      {{ comment.author.full_name }}
    </a>
    {{ comment.body }}
  </p>
</li>

app/templates/users/_extra-profile-info.html
{% if current_user != user %}
  {% if current_user.is_following(user) %}
  <a class="profile-follow-btn btn btn-gradient-green" href="{{ url_for('users.user_action', username=user.username, action='unfollow') }}">
    <i class="fa fa-user-minus"></i> Unfollow
  </a>
  {% else %}
  <a class="profile-follow-btn btn btn-gradient-gray" href="{{ url_for('users.user_action', username=user.username, action='follow') }}">
    <i class="fa fa-user-plus"></i> Follow
  </a>
  {% endif %}
{% endif %}
<div class="extra-profile-info main-container">
  {% if user.bio %}
  <p class="profile-bio">{{ user.bio }}</p>
  {% endif %}
  {% if user.location %}
  <p class="profile-user-location"><i class="fa fa-map-marker-alt"></i> {{ user.location }}</p>
  {% endif %}
  {% if user.website_url %}
  <p class="profile-website-url">
    <i class="fa fa-link"></i>
    <a href="{{ user.website_url|prepend_url }}">{{ user.website_url|truncate(28) }}</a>
  </p>
  {% endif %}
  <p class="profile-joined">
    <i class="fa fa-calendar-alt"></i>
    Joined
    {{ moment(user.created).format('MMMM YYYY') }}
  </p>
</div><!--//END .extra-info .main-container-->

app/templates/users/_list-user.html
<li>
  <a class="profile-picture" href="{{ url_for('users.profile', username=list_user.username) }}">
    <img src="{{ url_for('static', filename='img/user/' + list_user.profile_picture) }}" width="30" height="30">
  </a>
  <a href="{{ url_for('users.profile', username=list_user.username) }}">
    {{ list_user.full_name }}
  </a>
  {% if current_user != list_user %}
    {% if current_user.is_following(list_user) %}
    <a class="btn btn-unfollow" href="{{ url_for('users.user_action', username=list_user.username, action='unfollow') }}">
      Unfollow
    </a>
    {% else %}
    <a class="btn btn-follow" href="{{ url_for('users.user_action', username=list_user.username, action='follow') }}">
      Follow
    </a>
    {% endif %}
  {% endif %}
</li>

app/templates/users/_list-user_bulky.html
<li>
  <a class="profile-picture" href="{{ url_for('users.profile', username=list_user.username) }}">
    <img src="{{ url_for('static', filename='img/user/' + list_user.profile_picture) }}" width="45" height="45">
  </a>
  <div class="name-and-follow-btn">
    <a class="user-name" href="{{ url_for('users.profile', username=list_user.username) }}">{{ list_user.full_name }}</a>
    {% if current_user != list_user %}
      {% if current_user.is_following(list_user) %}
      <a class="btn btn-unfollow" href="{{ url_for('users.user_action', username=list_user.username, action='unfollow') }}">Unfollow</a>
      {% else %}
      <a class="btn btn-follow" href="{{ url_for('users.user_action', username=list_user.username, action='follow') }}">Follow</a>
      {% endif %}
    {% endif %}
  </div><!--//END .name-and-follow-button-->
</li>

app/templates/users/_post.html
  <li>
    <a class="profile-picture" href="{{ url_for('users.profile', username=post.author.username) }}">
      <img src="{{ url_for('static', filename='img/user/' + post.author.profile_picture) }}" width="45" height="45">
    </a>
    <div class="post-controls">
      <div class="post-likes">
        {% if current_user.has_liked_post(post) %}
        <a href="{{ url_for('users.post_action', post_id=post.id, action='unlike') }}"><i class="fa fa-heart"></i></a>
        {% else %}
        <a href="{{ url_for('users.post_action', post_id=post.id, action='like') }}"><i class="far fa-heart"></i></a>
        {% endif %}
        <a class="post-like-count" href="{{ url_for('users.post', post_id=post.id) }}">
          {{ post.active_likes.count() }}
        </a>
      </div><!--//END .post-likes-->
      <a href="{{ url_for('users.post', post_id=post.id) }}">
        {% if current_user.has_commented_post(post) %}
        <i class="fas fa-comment"></i>
        {% else %}
        <i class="far fa-comment"></i>
        {% endif %}
        <span class="post-comment-count">{{ post.active_comments.count() }}</span>
      </a>
      {% if current_user == post.author %}
      <a href="{{ url_for('users.post_edit', post_id=post.id) }}"><i class="far fa-edit"></i></a>
      {% endif %}
      {% if current_user == post.author or post.recipient_id == current_user.id %}
      <a class="delete-post" href="{{ url_for('users.post_action', post_id=post.id, action='delete') }}">
        <i class="fa fa-trash-alt"></i>
      </a>
      {% endif %}
    </div><!--//END .post-controls-->
    {% if post.edits.count() %}
    <a class="post-edits" href="{{ url_for('users.post_edit', post_id=post.id) }}">edited</a>
    {% endif %}
    <div class="main-container">
      <div class="post-header">
        <a href="{{ url_for('users.profile', username=post.author.username) }}">
          {{ post.author.full_name }}
        </a>
        {{ moment(post.created).fromNow() }}
      </div><!--//END .post-header-->
      <p>{{ post.body }}</p>
    </div><!--//END .main-container-->
  </li>

app/templates/users/_profile-info.html
<a class="name-and-profile-picture" href="{{ url_for('users.profile', username=user.username) }}">
  <img src="{{ url_for('static', filename='img/user/' + user.profile_picture) }}" width="55" height="55">
  <h2>{{ user.full_name }}</h2>
</a>
<div class="post-and-follow-count">
  <a href="{{ url_for('users.my_posts', username=user.username) }}">
    Posts <span>{{ user.my_posts.count() }}</span>
  </a>
  <a href="{{ url_for('users.followers', username=user.username) }}">
     Followers <span>{{ user.get_followers.count() }}</span>
  </a>
  <a href="{{ url_for('users.following', username=user.username) }}">
    Following <span>{{ user.get_followed.count() }}</span>
  </a>
</div><!--//END .post-and-follow-count-->

app/templates/users/_recent-posts.html
<div class="header-group">
  <i class="fas fa-book"></i>
  <h3>Recent posts you may be interested in</h3>
</div>
{% if unfollowed_posts %}
<ul class="recent-posts">
  {% for post in unfollowed_posts %}
  <li>
    <a class="recent-posts-header" href="{{ url_for('users.profile', username=post.author.username) }}">
      <img src="{{ url_for('static', filename='img/user/' + post.author.profile_picture) }}" width="30" height="30">
      <span>{{ post.author.full_name }}</span>
    </a>
    <p>{{ post.body|truncate }}</p>
  </li>
  {% endfor %}
</ul><!--//END .recent-posts-->
{% else %}
<p>No unfollowed recent posts to show. You are following everyone!</p>
{% endif %}

app/templates/users/_who-to-follow.html
<div class="header-group">
  <i class="fa fa-user-circle"></i>
  <h3>Who to follow</h3>
</div><!--//END .header-group-->
{% if current_user.unfollowed_users.count() %}
<ul class="list-users-bulky">
  {% for unfollowed_user in current_user.unfollowed_users %}
  {% set list_user = unfollowed_user %}
  {% include "users/_list-user_bulky.html" %}
  {% endfor %}
</ul><!--//END .who-to-follow-list-->
{% else %}
<p>No users to show. You are following everyone!</p>
{% endif %}

app/templates/users/following.html
{% extends "base.html" %}
{% from "_macros.html" import render_pagination %}

{% block content %}
<div class="profile grid responsive-container">
  <div class="grid-profile-info main-container">
    {% include "users/_profile-info.html" %}
  </div><!--//END .grid-profile-info .main-container-->
  <div class="grid-extra-profile-info">
    {% include "users/_extra-profile-info.html" %}
  </div><!--//END .grid-extra-profile-info-->
  <div class="grid-main">
    {{ render_pagination(following, 'users.following', username=user.username) }}
    <div class="main-container">
      <div class="header-group">
        <i class="fas fa-user"></i>
        <h3>Following</h3>
        <a class="back-to-page" href="{{ url_for('users.profile', username=user.username) }}">
          <i class="fa fa-chevron-left"></i> Back to {{ user.first_name }}'s profile
        </a>
      </div><!--//END .header-group-->
      {% if following.items %}
      <ul class="list-users">
        {% for list_user in following.items %}
        {% include "users/_list-user.html" %}
        {% endfor %}
      </ul><!--//END .list-users-->
      {% else %}
      <p class="card">
        {% if current_user == user %}
        You are not following anyone.
        {% else %}
        {{ user.first_name }} isn't following anyone.
        {% endif %}
      </p>
      {% endif %}
    </div><!--//END .main-container-->
    {{ render_pagination(following, 'users.following', username=user.username) }}
  </div><!--//END .grid-main-->
  <div class="grid-who-to-follow main-container">
    {% include "users/_who-to-follow.html" %}
  </div><!--//END .grid-who-to-folow .main-container-->
</div><!--//END .profile-and-home .grid .responsive-container-->
{% endblock %}

app/templates/users/home.html
{% extends "base.html" %}
{% from "_macros.html" import render_pagination %}
{% block page_title %}{{ APP_NAME }}{% endblock %}

{% block content %}
<div class="home grid responsive-container">
  <div class="grid-profile-info main-container">
    {% include "users/_profile-info.html" %}
  </div><!--//END .grid-profile-info .main-container-->
  <div class="grid-recent-posts main-container">
    {% include "users/_recent-posts.html" %}
  </div><!--//END .grid-recent-posts .main-container-->
  <div class="grid-main">
    {% include "users/_post-form.html" %}
    {{ render_pagination(posts, 'users.home') }}
    {% if posts.items %}
    <ul class="post-list">
      {% for post in posts.items %}
      {% include "users/_post.html" %}
      {% endfor %}
    </ul>
    {% else %}
    <p class="card">
      No posts to show. Post something, or start 
      <a href="{{ url_for('users.search') }}">following</a>
      some people.
    </p><!--//END .card-->
    {% endif %}
    {{ render_pagination(posts, 'users.home') }}
  </div><!--//END .grid-main-->
  <div class="grid-who-to-follow main-container">
    {% include "users/_who-to-follow.html" %}
  </div><!--//END .grid-who-to-follow .main-container-->
</div><!--//END .profile-and-home .grid .responsive-container-->
{% endblock %}

app/templates/users/notifications.html
{% extends "base.html" %}
{% from "_macros.html" import render_pagination %}

{% block content %}
<div class="notifications">
  <div class="main-container">
    <div class="header-group">
      <i class="fas fa-bell"></i>
      <h3>Notifications</h3>
    </div><!--//END .header-group-->
    {% if notifications %}
    <ul class="notification-list">
      {% for n in notifications %}
      {% set notifier_url = url_for('users.profile', username=n.notifier.username) %}
      <li>
        {% if n.name == 'follow' %}
        <a href="{{ notifier_url }}">{{ n.notifier.full_name }}</a>
        started following you

        {% elif n.name == 'post' %}
        <a href="{{ notifier_url }}">{{ n.notifier.full_name }}</a>
        posted on your wall

        {% elif n.name == 'post_like' %}
        <a href="{{ notifier_url }}">{{ n.notifier.full_name }}</a>
        liked your
        <a href="{{ url_for('users.post', post_id=n.post.id) }}">post</a>

        {% elif n.name == 'post_like_wall' %}
        <a href="{{ notifier_url }}">{{ n.notifier.full_name }}</a>
        liked a
        <a href="{{ url_for('users.post', post_id=n.post.id) }}">post</a>
        on your wall

        {% elif n.name == 'comment' %}
        <a href="{{ notifier_url }}">{{ n.notifier.full_name }}</a>
        <a href="{{ url_for('users.comment', comment_id=n.comment.id) }}">commented</a>
        on your
        <a href="{{ url_for('users.post', post_id=n.comment.post.id) }}">post</a>

        {% elif n.name == 'comment_wall' %}
        <a href="{{ notifier_url }}">{{ n.notifier.full_name }}</a>
        <a href="{{ url_for('users.comment', comment_id=n.comment.id) }}">commented</a>
        on a
        <a href="{{ url_for('users.post', post_id=n.comment.post.id) }}">post</a>
        on your wall

        {% elif n.name == 'comment_like' %}
        <a href="{{ notifier_url }}">{{ n.notifier.full_name }}</a>
        liked your
        <a href="{{ url_for('users.comment', comment_id=n.comment.id) }}">comment</a>

        {% elif n.name == 'comment_like_post' %}
        <a href="{{ notifier_url }}">{{ n.notifier.full_name }}</a>
        liked a
        <a href="{{ url_for('users.comment', comment_id=n.comment.id) }}">comment</a>
        on your
        <a href="{{ url_for('users.post', post_id=n.comment.post.id) }}">post</a>

        {% elif n.name == 'comment_like_wall' %}
        <a href="{{ notifier_url }}">{{ n.notifier.full_name }}</a>
        liked a
        <a href="{{ url_for('users.comment', comment_id=n.comment.id) }}">comment</a>
        of a
        <a href="{{ url_for('users.post', post_id=n.comment.post.id) }}">post</a>
        on your wall
        {% endif %}

        {{ moment(n.created).fromNow() }}
      </li>
      {% endfor %}
    </ul><!--//END .notification-list-->
    {% else %}
    <p>You do not have any notifications to show.</p>
    {% endif %}
  </div><!--//END .main-container-->
</div><!--//END .notifications-->
{% endblock %}